project:
  type: book
  output-dir: docs
  
execute:
  freeze: auto

book:
  favicon: logo-icon.svg
  title: "Epidemiological data analysis for babies"
  author:
    - name: Thinh Ong
      url: https://drthinhong.com/
      orcid: 0000-0001-6772-9291
  date: "08/08/2024"
  chapters:
    - index.qmd
    - age.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: [cosmo, theme.scss]
    code-overflow: wrap
    code-copy: true
    fig-format: svg
    df-print: paged
    toc-depth: 5
    toc-expand: 3

